version: '3.8'

services:
  db:
    image: postgres:15
    container_name: inovait_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: bd_principal
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"

volumes:
  db-data:
